# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_projtmpl.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProjTempl(object):
    def setupUi(self, ProjTempl):
        ProjTempl.setObjectName("ProjTempl")
        ProjTempl.resize(492, 277)
        self.gridLayout = QtWidgets.QGridLayout(ProjTempl)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(ProjTempl)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.url_check = QtWidgets.QRadioButton(ProjTempl)
        self.url_check.setChecked(True)
        self.url_check.setAutoExclusive(False)
        self.url_check.setObjectName("url_check")
        self.horizontalLayout_3.addWidget(self.url_check)
        self.localFiles_check = QtWidgets.QRadioButton(ProjTempl)
        self.localFiles_check.setChecked(True)
        self.localFiles_check.setAutoExclusive(False)
        self.localFiles_check.setObjectName("localFiles_check")
        self.horizontalLayout_3.addWidget(self.localFiles_check)
        self.localDir_check = QtWidgets.QRadioButton(ProjTempl)
        self.localDir_check.setChecked(True)
        self.localDir_check.setAutoExclusive(False)
        self.localDir_check.setObjectName("localDir_check")
        self.horizontalLayout_3.addWidget(self.localDir_check)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ProjTempl)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.infoLocationPath = QtWidgets.QLineEdit(ProjTempl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoLocationPath.sizePolicy().hasHeightForWidth())
        self.infoLocationPath.setSizePolicy(sizePolicy)
        self.infoLocationPath.setObjectName("infoLocationPath")
        self.horizontalLayout_2.addWidget(self.infoLocationPath)
        self.templatesInfoPath_btn = QtWidgets.QPushButton(ProjTempl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templatesInfoPath_btn.sizePolicy().hasHeightForWidth())
        self.templatesInfoPath_btn.setSizePolicy(sizePolicy)
        self.templatesInfoPath_btn.setMinimumSize(QtCore.QSize(10, 0))
        self.templatesInfoPath_btn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.templatesInfoPath_btn.setObjectName("templatesInfoPath_btn")
        self.horizontalLayout_2.addWidget(self.templatesInfoPath_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.loadData_btn = QtWidgets.QPushButton(ProjTempl)
        self.loadData_btn.setObjectName("loadData_btn")
        self.horizontalLayout_2.addWidget(self.loadData_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(ProjTempl)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.project_comboBox = QtWidgets.QComboBox(ProjTempl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_comboBox.sizePolicy().hasHeightForWidth())
        self.project_comboBox.setSizePolicy(sizePolicy)
        self.project_comboBox.setObjectName("project_comboBox")
        self.horizontalLayout_5.addWidget(self.project_comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ProjTempl)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.infoLocation_comboBox = QtWidgets.QComboBox(ProjTempl)
        self.infoLocation_comboBox.setObjectName("infoLocation_comboBox")
        self.infoLocation_comboBox.addItem("")
        self.infoLocation_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.infoLocation_comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.create_btn = QtWidgets.QPushButton(ProjTempl)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_6.addWidget(self.create_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.close_btn = QtWidgets.QPushButton(ProjTempl)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_6.addWidget(self.close_btn)
        self.gridLayout.addLayout(self.horizontalLayout_6, 4, 0, 1, 1)

        self.retranslateUi(ProjTempl)
        self.close_btn.clicked.connect(ProjTempl.close)
        QtCore.QMetaObject.connectSlotsByName(ProjTempl)

    def retranslateUi(self, ProjTempl):
        _translate = QtCore.QCoreApplication.translate
        ProjTempl.setWindowTitle(_translate("ProjTempl", "Project from template creator"))
        self.label_3.setText(_translate("ProjTempl", "Origins: "))
        self.url_check.setText(_translate("ProjTempl", "Url"))
        self.localFiles_check.setText(_translate("ProjTempl", "Loca files"))
        self.localDir_check.setText(_translate("ProjTempl", "Local dir"))
        self.label_2.setText(_translate("ProjTempl", "Templates info path: "))
        self.templatesInfoPath_btn.setText(_translate("ProjTempl", "..."))
        self.loadData_btn.setText(_translate("ProjTempl", "Load"))
        self.label_5.setText(_translate("ProjTempl", "Project: "))
        self.label.setText(_translate("ProjTempl", "Templates info location: "))
        self.infoLocation_comboBox.setItemText(0, _translate("ProjTempl", "URL"))
        self.infoLocation_comboBox.setItemText(1, _translate("ProjTempl", "Local"))
        self.create_btn.setText(_translate("ProjTempl", "Create"))
        self.close_btn.setText(_translate("ProjTempl", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjTempl = QtWidgets.QDialog()
    ui = Ui_ProjTempl()
    ui.setupUi(ProjTempl)
    ProjTempl.show()
    sys.exit(app.exec_())

